=== BackupTheBerlios/xgngeo/data/rominfos.dtd
<?xml version='1.0' encoding='utf-8'?>
 
<!-- 
  DTD for roms info in GGF and XGngeo!
-->

<!ELEMENT roms (info+)>
<!ELEMENT info (set, manufacturer,players,genre,year,size,desc,rating)>
<!ELEMENT set (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT players (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT rating (#PCDATA)>

=== BackupTheBerlios/xgngeo/data/rominfos.xml
<?xml version="1.0" standalone="yes"?>
<!DOCTYPE roms SYSTEM "rominfos.dtd">
<roms>
<info>
	<set>2020bb</set>
	<manufacturer>SNK/Pallas</manufacturer>
	<players>1</players>
	<genre>Baseball</genre>
	<year>1991</year>
	<size>46</size>
	<desc>Another NeoGeo Baseball game following on from the success of the acclaimed BaseBall Stars Professional. This game takes a futuristic approach to the sport, in that over-the-top japanese kind of way. The graphics are very colourful and fairly well drawn, and unlike some of the other earlier neogeo games, the animation is mostly quite good. While this game tries to be futuristic with its flashy graphics, at heart its not that different from Baseball Stars Professional. I am not a great follower of baseball myself, as we dont see much of it in the UK, but from what I can tell the game remains fairly accurate to the sport. As far as sound goes there are the usual whacks, cheers and some computerised responses from the umpire. As for the home version (set 2), the differences are hardly noticeable. Overall if you like Baseball then youll probably enjoy this. </desc>
	<rating>12</rating>
</info>
<info>
	<set>3countb</set>
	<manufacturer>SNK</manufacturer>
	<players>1 or 2</players>
	<genre>1on1 Wrestling</genre>
	<year>1993</year>
	<size>106</size>
	<desc>While there is a huge number of fighting games for the NeoGeo, as far as I know this is the only Wrestling game. The graphics are suitably bold and large and reflect the typical atmosphere of a wrestling match. The Zoom effect which was first used in Art of Fighting is also put to good use. Sound effects are what you would expect from a wrestling match, each wrestler has their own range of grunts groans and screams, and there is a voice over commentary before every match. There are 10 wrestlers to choose from each with a suitably over-the-top range of moves and outfits in the traditional american wrestling style and the game plays convincingly, with grapples, holds, throws, punches and kicks as well as special attacks ranging from suplexes to breathing fire. Overall this is a good solid playable game and should especially appeal to wrestling fans, particularly as their choice is somewhat limited.</desc>
	<rating>14</rating>
</info>
<info>
	<set>alpham2</set>
	<manufacturer>SNK</manufacturer>
	<players>1 or 2</players>
	<genre>Vertical Scrolling Shooter</genre>
	<year>1991</year>
	<size>47</size>
	<desc>This game features an unusual menu based power-up which can make the controls seem a little cumbersome at first, its all too easy to get your ship destroyed whilst trying to use the menus, but with practice the game does play fairly well. It does however look a little dated when compared with some of the later games.</desc>
	<rating>13</rating>
</info>
<info>
	<set>androdun</set>
	<manufacturer>Visco</manufacturer>
	<players>1 or 2</players>
	<genre>Horizontal Scrolling Shooter</genre>
	<year>1992</year>
	<size>32</size>
	<desc> This shooter has a very cartoon-like feel to it which is slightly unusual for this kind of game, in some places it looks almost *cute*. Its not an over-the-top blast frenzy like some other neo shooters but seems to play more like r-type, one interesting feature is the weapons, your ship comes pre equipped with a range of selectable weapons so you dont have to rely on a feeble weapon until a powerup comes along. You also continue from where you left off when your ships are destroyed, rather than having to repeat half the level again and again when you reach a difficult part</desc>
	<rating>12</rating>
</info>
<info>
	<set>aodk</set>
	<manufacturer>ADK/SNK</manufacturer>
	<players>1 or 2</players>
	<genre>1on1 Fighting</genre>
	<year>1994</year>
	<size>178</size>
	<desc>One of the More unusual NeoGeo fighting games, its a cross between a scrolling fighter and a one on one fighter as you can walk in-to and out-of the backgrounds, so it has a slightly wierd feel, but it plays well once you get used to it.</desc>
	<rating>14</rating>
</info>
<info>
	<set>aof</set>
	<manufacturer>SNK</manufacturer>
	<players>1 or 2</players>
	<genre>1on1 Fighting</genre>
	<year>1992</year>
	<size>102</size>
	<desc>This was one of the first fighting games to appear on the NeoGeo it features enormous character sprites and a zoom feature which gives a close up view of the action when the characters are near to each other. Personally I really like this game, but thats probably because I remember playing it years ago when it first appeared, there was a great atmosphere to the single player story mode, but by todays standards it is somewhat limited, for example the single player mode only has two playable characters, and there is no true combo system, but the game is still very playable it is more of a slower paced tactical beat-em up than some of the newer fighting games such as the King of Fighters series. The sound features the usual beat em up style sound effects along with a bit of speech for some of the special moves. There are plenty of beat em ups for the NeoGeo and this is by no means the best of them, but it does have some unique features which make it more than worth playing.</desc>
	<rating>13</rating>
</info>
<info>
	<set>aof2</set>
	<manufacturer>SNK</manufacturer>
	<players>1 or 2</players>
	<genre>1on1 Fighting</genre>
	<year>1994</year>
	<size>178</size>
	<desc>There were a number of criticisms of the original Art of Fighting, Mainly the lack of characters in the single player game and the speed of the game. With the sequel SNK gave the players what they asked for- 12 Playable Characters, each with a story of their own in the single player game and overall faster gameplay. In terms of Graphics and sound the style remains quite similar to the original but with some general improvements to the quality, also the game is still more tactic based than combination based, I cant seem to find a proper combo system such as in the king of fighters games. Overall It is a good game with many improvements over the original, but I cant help but feel that some of the atmosphere of the first game has been lost in this sequel.</desc>
	<rating>16</rating>
</info>
<info>
	<set>aof3</set>
	<manufacturer>SNK</manufacturer>
	<players>1 or 2</players>
	<genre>1on1 Fighting</genre>
	<year>1996</year>
	<size>298</size>
	<desc>This is the third and (I think) final game in the Art of Fighting series. The game has a differnent look and feel about it to its predecessors. Probably the first thing people will notice is that the graphical style has changed and the animation has been massively improved, every character has been motion captured from a real person for ultra-smoooooth movements, it is probably the best animation in any NeoGeo game ever, even better than the newer King of Fighters games. The game also continues the story theme of the previous Art of fighting games but again improves upon it, its now almost like watching a film. The sound effects and music remain consistent with the previous games but have been jazzed up for the third incarnation. Fans of the first two games will immediately notice that Aof3 plays rather differently than before, the zoom-in feature is not so pronounced and the new combo system allows you to *juggle* your opponent with hits in the air, the controls can feel strange at first but you soon get used to it and find that it is a very playable game.</desc>
	<rating>17</rating>
</info>
<info>
	<set>bakatono</set>
	<manufacturer>Monolith</manufacturer>
	<players>1</players>
	<genre>Mahjong/RPG</genre>
	<year>1991</year>
	<size>48</size>
	<desc>This game appears to be a hybrid of japanese mahjong and a role playing game, unfortunately almost all the ingame text is in japanese, thus making it somewhat difficult to play.</desc>
	<rating>?</rating>
</info>
<info>
	<set>bangbead</set>
	<manufacturer>Visco</manufacturer>
	<players>1 or 2</players>
	<genre>Airhockey</genre>
	<year>2000</year>
	<size>170</size>
	<desc>This game appears to be very similar to both Windjammers and Battle Flipshot, continuing the same airhockey theme- hit all of your opponents markers with the ball to win whilst guarding your own.</desc>
	<rating>?</rating>
</info>
<info>
	<set>bjourney</set>
	<manufacturer>Alpha Denshi</manufacturer>
	<players>1</players>
	<genre>Platform</genre>
	<year>1990</year>
	<size>50</size>
	<desc>This is one of those cute and colourful platform games, which you either love or hate, I suppose its aimed at kids, but then how many kids could afford almost $700 for the console and game? It plays ok, but is nothing special, the makers have tried to introduce some RPG-like elements into it such as shops where you can buy items to aid your quest, but it is fairly simplistic.</desc>
	<rating>9</rating>
</info>
<info>
	<set>blazstar</set>
	<manufacturer>Yumekobo</manufacturer>
	<players>1 or 2</players>
	<genre>Horizontal Scrolling Shooter</genre>
	<year>1998</year>
	<size>346</size>
